#### steps to create Ml Model

###### 1) EDA- exploratory Data analysis
###### 2) Data Cleaning
###### 3) Data preprocessing 
###### 4) Feature Engineering 
###### 5) Feature Selection

In [23]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 


warnings.filterwarnings("ignore")

In [24]:
data = pd.read_csv("insurance (1).csv")
data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

#### Data cleaning and preprocessing

In [25]:
df_cleaned = data.copy()

In [26]:
df_cleaned.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [27]:
df_cleaned.shape

(1338, 7)

In [28]:
df_cleaned.drop_duplicates(inplace=True)

In [29]:
df_cleaned.shape

(1337, 7)

In [30]:
df_cleaned.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [31]:
df_cleaned.dtypes

age           int64
sex             str
bmi         float64
children      int64
smoker          str
region          str
charges     float64
dtype: object

In [32]:
df_cleaned["sex"].value_counts()

sex
male      675
female    662
Name: count, dtype: int64

In [33]:
# doing label encoding
df_cleaned["sex"]= df_cleaned["sex"].map({"male":0 , "female": 1})

In [34]:
df_cleaned.head()

   age  sex     bmi  children smoker     region      charges
0   19    1  27.900         0    yes  southwest  16884.92400
1   18    0  33.770         1     no  southeast   1725.55230
2   28    0  33.000         3     no  southeast   4449.46200
3   33    0  22.705         0     no  northwest  21984.47061
4   32    0  28.880         0     no  northwest   3866.85520

In [35]:
df_cleaned["smoker"].value_counts()

smoker
no     1063
yes     274
Name: count, dtype: int64

In [36]:
df_cleaned["smoker"]= df_cleaned["smoker"].map({"no":0 , "yes": 1})

In [37]:
df_cleaned.head()

   age  sex     bmi  children  smoker     region      charges
0   19    1  27.900         0       1  southwest  16884.92400
1   18    0  33.770         1       0  southeast   1725.55230
2   28    0  33.000         3       0  southeast   4449.46200
3   33    0  22.705         0       0  northwest  21984.47061
4   32    0  28.880         0       0  northwest   3866.85520

In [38]:
df_cleaned.rename(columns={
    "sex": "isFemale",
    "smoker":"isSmoker"
}, inplace=True)

In [39]:
df_cleaned.head()

   age  isFemale     bmi  children  isSmoker     region      charges
0   19         1  27.900         0         1  southwest  16884.92400
1   18         0  33.770         1         0  southeast   1725.55230
2   28         0  33.000         3         0  southeast   4449.46200
3   33         0  22.705         0         0  northwest  21984.47061
4   32         0  28.880         0         0  northwest   3866.85520

In [40]:
df_cleaned["region"].value_counts()

region
southeast    364
southwest    325
northwest    324
northeast    324
Name: count, dtype: int64

In [41]:
df_cleaned=pd.get_dummies(df_cleaned,columns=["region"],drop_first=True)

In [42]:
 df_cleaned=df_cleaned.astype(int)

In [43]:
df_cleaned

,age,isFemale,bmi,children,isSmoker,charges,region_northwest,region_southeast,region_southwest
0,19,1,27,0,1,16884,0,0,1
1,18,0,33,1,0,1725,0,1,0
2,28,0,33,3,0,4449,0,1,0
3,33,0,22,0,0,21984,1,0,0
4,32,0,28,0,0,3866,1,0,0
...,...,...,...,...,...,...,...,...,...
1333,50,0,30,3,0,10600,1,0,0
1334,18,1,31,0,0,2205,0,0,0
1335,18,1,36,0,0,1629,0,1,0
1336,21,1,25,0,0,2007,0,0,1
1337,61,1,29,0,1,29141,1,0,0