#### merging joining and concatenation

In [2]:
import numpy as np
import pandas as pd

##### merging of 2 dataframes

In [3]:
employees = pd.DataFrame({
    "employees_id": [1,2,3,4,5],
    "name": ["john","Anna","peter","Linda","Bob"],
    "department": ["HR","IT","finance","IT","HR"]
})
salaries = pd.DataFrame({
    "employees_id":[1,2,3,6,7],
    "salary":[60000,80000,65000,70000,90000],
    "bonus":[5000,10000,7000,8000,12000]
})

In [4]:
employees

   employees_id   name department
0             1   john         HR
1             2   Anna         IT
2             3  peter    finance
3             4  Linda         IT
4             5    Bob         HR

In [5]:
salaries

   employees_id  salary  bonus
0             1   60000   5000
1             2   80000  10000
2             3   65000   7000
3             6   70000   8000
4             7   90000  12000

In [6]:
pd.merge(employees,salaries)

   employees_id   name department  salary  bonus
0             1   john         HR   60000   5000
1             2   Anna         IT   80000  10000
2             3  peter    finance   65000   7000

In [7]:
pd.merge(employees,salaries,on="employees_id",how="inner")

   employees_id   name department  salary  bonus
0             1   john         HR   60000   5000
1             2   Anna         IT   80000  10000
2             3  peter    finance   65000   7000

In [8]:
pd.merge(employees,salaries,on="employees_id",how="outer")

   employees_id   name department   salary    bonus
0             1   john         HR  60000.0   5000.0
1             2   Anna         IT  80000.0  10000.0
2             3  peter    finance  65000.0   7000.0
3             4  Linda         IT      NaN      NaN
4             5    Bob         HR      NaN      NaN
5             6    NaN        NaN  70000.0   8000.0
6             7    NaN        NaN  90000.0  12000.0

In [9]:
pd.merge(employees,salaries,on="employees_id",how="left")

   employees_id   name department   salary    bonus
0             1   john         HR  60000.0   5000.0
1             2   Anna         IT  80000.0  10000.0
2             3  peter    finance  65000.0   7000.0
3             4  Linda         IT      NaN      NaN
4             5    Bob         HR      NaN      NaN

In [10]:
pd.merge(employees,salaries,on="employees_id",how="right")

   employees_id   name department  salary  bonus
0             1   john         HR   60000   5000
1             2   Anna         IT   80000  10000
2             3  peter    finance   65000   7000
3             6    NaN        NaN   70000   8000
4             7    NaN        NaN   90000  12000

##### concatenation of two dataframes

In [11]:
df1= pd.DataFrame({
    "A": ["A0","A1","A2"],
    "B": ["B0","B1","B2"],
    "C": ["C0","C1","C2"]
})
df2=pd.DataFrame({
    "A": ["A3","A4","A5"],
    "B": ["B3","B4","B5"],
    "C": ["C3","C4","C5"]
})

In [12]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [13]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [14]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [15]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

##### joining

In [18]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [19]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [21]:
df3=pd.DataFrame({
    "Name": ["Alice","john","tony"]
},index=[1,2,3])

In [23]:
df4=pd.DataFrame({
    "Score":[85,80,75]
},index=[2,3,4])

In [24]:
df3

    Name
1  Alice
2   john
3   tony

In [25]:
df4

   Score
2     85
3     80
4     75

In [26]:
df3.join(df4)

    Name  Score
1  Alice    NaN
2   john   85.0
3   tony   80.0

In [27]:
df4.join(df3)

   Score  Name
2     85  john
3     80  tony
4     75   NaN

In [28]:
df3.join(df4 , how="outer")

    Name  Score
1  Alice    NaN
2   john   85.0
3   tony   80.0
4    NaN   75.0