## pandas tutorial

In [4]:
import numpy as np
import pandas as pd

In [5]:
labels=["a","b","c"]
my_List=[10,20,30]
arr= np.array([10,20,30])
d={1:10,2:20,3:30}

In [6]:
pd.Series(my_List)

0    10
1    20
2    30
dtype: int64

In [7]:
pd.Series(arr,index=labels)

a    10
b    20
c    30
dtype: int64

In [8]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

##### dataframe

In [9]:
data= {
    "Name": ["john","Anna","Peter","Linda"],
    "Age":[28,34,29,42],
    "City":["new york","paris","berlin","london"],
    "Salary":[65000,7000,25000,50000]
}

In [10]:
 df=pd.DataFrame(data)

In [11]:
 df

    Name  Age      City  Salary
0   john   28  new york   65000
1   Anna   34     paris    7000
2  Peter   29    berlin   25000
3  Linda   42    london   50000

In [12]:
data_list=[
     ["john",34,"USA",80000],
    [ "Anna",28,"India",70000],
    [  "Peter",34,"new york", 25000],
      ["Linda",34,"Berlin", 50000]
]
df2=pd.DataFrame(data_list)

In [13]:
df2

       0   1         2      3
0   john  34       USA  80000
1   Anna  28     India  70000
2  Peter  34  new york  25000
3  Linda  34    Berlin  50000

In [14]:
columns=["Name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns=columns)

In [15]:
df2

    Name  Age      City  Salary
0   john   34       USA   80000
1   Anna   28     India   70000
2  Peter   34  new york   25000
3  Linda   34    Berlin   50000

##### selection and indexing of columns

In [16]:
df2["Name"]

0     john
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [17]:
df2["Age"]

0    34
1    28
2    34
3    34
Name: Age, dtype: int64

In [18]:
df2[["Name","City"]]

    Name      City
0   john       USA
1   Anna     India
2  Peter  new york
3  Linda    Berlin

#### Creating a new columns

In [19]:
df2["Designation"]=["doctor","engineer","doctor","engineer"]

In [20]:
df2

    Name  Age      City  Salary Designation
0   john   34       USA   80000      doctor
1   Anna   28     India   70000    engineer
2  Peter   34  new york   25000      doctor
3  Linda   34    Berlin   50000    engineer

In [21]:
df2.drop("Designation",axis=1)

    Name  Age      City  Salary
0   john   34       USA   80000
1   Anna   28     India   70000
2  Peter   34  new york   25000
3  Linda   34    Berlin   50000

In [22]:
df2

    Name  Age      City  Salary Designation
0   john   34       USA   80000      doctor
1   Anna   28     India   70000    engineer
2  Peter   34  new york   25000      doctor
3  Linda   34    Berlin   50000    engineer

In [23]:
df2.drop(0,axis=0)

    Name  Age      City  Salary Designation
1   Anna   28     India   70000    engineer
2  Peter   34  new york   25000      doctor
3  Linda   34    Berlin   50000    engineer

#### selecting rows

In [24]:
df2.loc[0]

Name             john
Age                34
City              USA
Salary          80000
Designation    doctor
Name: 0, dtype: object

##### selecting subsets of rows and columns

In [25]:
df2.loc[[0,1]][["City","Salary"]]

    City  Salary
0    USA   80000
1  India   70000

In [26]:
df2.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   34
3  Linda   34

##### conditional selections

In [27]:
df2

    Name  Age      City  Salary Designation
0   john   34       USA   80000      doctor
1   Anna   28     India   70000    engineer
2  Peter   34  new york   25000      doctor
3  Linda   34    Berlin   50000    engineer

In [28]:
df2[df2["Age"]>30]

    Name  Age      City  Salary Designation
0   john   34       USA   80000      doctor
2  Peter   34  new york   25000      doctor
3  Linda   34    Berlin   50000    engineer

In [31]:
df2[(df2["Age"]>30 )& (df2["City"]== "USA")]

   Name  Age City  Salary Designation
0  john   34  USA   80000      doctor